version: '3'

services:
  wordpress:
    image: wordpress:latest
    container_name: wpsr_wordpress
    restart: always
    ports:
      - 8080:80
    env_file:
      - config.env
    volumes: 
      - wordpress_volume:/var/www/html/wp-content
    networks:
      - wpsr_network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: wpsr_mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - config.env
    volumes: 
      - mysql_volume:/var/lib/mysql
    networks:
      wpsr_network:
        ipv4_address: 172.80.0.5
      
volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wp-content
  mysql_volume:
    name: mysql_volume
    driver: local

networks:
  wpsr_network:
    name: wpsr_network
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/16